### ISSUE TITLE
Enginemanager on https

### ISSUE THREAD

**Issue by nlmaca** [robymus/wowza-letsencrypt-converter#3]
EDIT: to soon to ask ;(). was trying for 2 days. 5 minutes after this post i found the problem. 
will add a link to my documentation when finished (this week), maybe users can use it. 

This is what i had to change in the startmgr.sh (only the last CMD part)
i changed the location of the jks file to where i placed it in the first place. so the jks is always on the same place;)

`CMD="$_EXECJAVA -Dcom.wowza.wms.ConfigURL=\"\" -Dcom.wowza.wms.ConfigHome=$WMSMGR_HOME -Djava.io.tmpdir=$WMSMGR_HOME/temp -Dlog4j.configuration=file://$WMSMGR_HOME/conf/winstone.properties -Djava.net.preferIPv4Stack=true -jar $WMSMGR_HOME/lib/wms-winstone-1.0.5-boot.jar --prefix=/enginemanager --defaultWebApp=/enginemanager --tempDirectory=$WMSMGR_HOME/temp  --webroot=$WMSMGR_HOME/temp --warfile=$WMSMGR_HOME/lib/WMSManager.war --httpPort=8088 --httpsPort=8090 --httpsKeyStore="/usr/local/WowzaStreamingEngine/conf/MY_SSL.jks" --httpsKeyStorePassword="secret" --directoryListings=false"`

then restart the enginemanager and you can access the backend also on SSL, although on port 8090, because that is what i set in the startmgr.sh
https://IP_ADDRESS:8090/enginemanager/login.htm

--- so below is solved --
I got the frontend working within wowza with your converter script and LetsEncrypt. Thx for that.  I was wondering though how you got the backend running on ssl?

http://IP_ADDRESS:8088/enginemanager/  >> http is ok. access ok
httpS://IP_ADDRESS/enginemanager/  >> https is ok. but shows only wowza license, no enginemanager login page.
Based on the wowza documentation i also have to change the Manager:
https://www.wowza.com/docs/how-to-connect-to-wowza-streaming-engine-manager-over-https

Just for example in the /usr/local/WowzaStreamingEngine/manager/bin/startmgr.sh you have to edit the line so it will pickup the https port. But as soon as i change that to the settings i think has to be set, the enginemanager doesnt want to start. 

`CMD="$_EXECJAVA -Dcom.wowza.wms.ConfigURL=\"\" -Dcom.wowza.wms.ConfigHome=$WMSMGR_HOME -Djava.io.tmpdir=$WMSMGR_HOME/temp -Dlog4j.configuration=file://$WMSMGR_HOME/conf/winstone.properties -Djava.net.pre    ferIPv4Stack=true -jar $WMSMGR_HOME/lib/wms-winstone-1.0.5-boot.jar --prefix=/enginemanager --defaultWebApp=/enginemanager --tempDirectory=$WMSMGR_HOME/temp  --webroot=$WMSMGR_HOME/temp --warfile=$WMSMGR_HOME/lib/WMSManager.war --httpPort=8088 --httpsPort=8090 --httpsKeyStore="$WMSMGR_HOME/conf/MY_SSL.jks" --httpsKeyStorePassword="secret" --ajp13Port=-1 --directoryListings=false"`

Changing the values with the quotes or without doesnt matter. I have the MY_SSL.jks file copied to the 
/usr/local/WowzaStreamingEngine/manager/conf directory so it should be able to use it.
My VHost.xml has https port on 443

**Comment by nlmaca** [comment]
promised a note: 
complete installation of LetsEncrypt on Wowza StreamingEngine. Credits in the tutorial for you of course. Couldn't have got it work without your conversion script. Thx again
If you want to delete the url thats fine by me, or delete the issue. I leave that to you.
https://vanmarion.nl/blog/blog/ssl-letsencrypt-wowza-4-x-server-frontend/

**Comment by robymus** [comment]
Great tutorial, I planned on writing one myself. I'm currently not using manager, so didn't think about it. As I see from your tutorial, it uses the jks file directly, so it's not possible to reload automatically when let's encrypt renews the certificate - but restarting the manager is probably not a big deal anyway. 

As for streaming engine, you also use the jks file directly in your wowza configuration, I suggest you don't do that - but instead use the <DomainToKeyStoreMapPath> and point to your generated jksmap.txt. When your certificate is renewed and you run the converter again, a new jksmap.txt file is written, Wowza Streaming Engine will notice the change of the map file and reload the certificates. If you use the jks files directly, they won't be reloaded and upon the certificate expiration/renewal, you have to restart the server. 

Currently I'm working on using simplifying the DTLS setup in Wowza Streaming Engine (for web-rtc preview), and writing a full tutorial on securing wowza was in my plans after that. I will try to look into alternative ways to setup the manager as well (with automatic certificate reloading, if it's at all possible)

**Comment by nlmaca** [comment]
Good point on the txt file. will see if i can change that. Restarting the enginemanager has less impact on the streaming part, (streams can run without it). If i run into problems or find something i will sure let you know.
