### ISSUE TITLE
letsencrypt module with Plesk

### ISSUE THREAD

**Issue by n0risc** [robymus/wowza-letsencrypt-converter#4]
# java -jar wowza-letsencrypt-converter-0.1.jar -v /usr/local/WowzaStreamingEngine/conf /usr/local/psa/var/modules/letsencrypt/etc/live
Converting certificates: /usr/local/psa/var/modules/letsencrypt/etc/live => /usr/local/WowzaStreamingEngine/conf
Reading example.com
Read error in example.com:Final chunk not closed
Error reading certificates, aborting without writing anything

The files are symlinked in the live directory to another directory, however the original .pem key files are not standard names.

cert.pem -> ../../archive/example.com/cert1.pem

**Comment by robymus** [comment]
Could you please check the files fullchain.pem and privkey.pem in the  /usr/local/psa/var/modules/letsencrypt/etc/live/example.com directory to see if they have ending

`-----END CERTIFICATE-----`
and
`-----END PRIVATE KEY-----`

markers, respectively? The error means that a certificate or private key has been opened with a BEGIN marker, but not closed at the end of file.

**Comment by n0risc** [comment]
I fixed the issue. The .pem files from Plesk add an extra line at the end of the markers.

**Comment by robymus** [comment]
I will update the parser soon to handle this case correctly. Thanks for reporting.

**Comment by n0risc** [comment]
You're welcome!

**Comment by robymus** [comment]
Sorry for the late response, I totally forgot this issue :)
I have added some test cases for trailing empty lines and it works correctly for me.
If you still have it at hand, or if you can reproduce it, could you please send a faulty pem file for testing?

**Comment by robymus** [comment]
Closed due to long inactivity.
